### ISSUE TITLE
Custom background does not work in IE7.

### ISSUE THREAD

**Issue by davidakennedy** [davidakennedy/accessible-zen#18]
Relates to #1. This is because our custom background styles are wrapped in a media query and those aren't picked up by IE8 and below. We can solve this with some targeted styles for IE.

``` css
.ie7 body.custom-background .site,
.ie8 body.custom-background .site {
    width: 80%;
}
```
